version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout

      - run:
          command: ./bin/setup

      - run:
          name: Changes
          command: |
            if [[ $(git status --porcelain) != '' ]]
            then
              git status
              exit 1
            fi
