Vagrant.configure(2) do |config|
  config.vm.synced_folder "#{ENV['HOME']}/workspace/config_files", '/home/vagrant/.config_files', nfs: true

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get install --yes git
  SHELL

  config.vm.provision 'shell', privileged: false, inline: '/home/vagrant/.config_files/bin/bootstrap'
end
