# ~/.bash_aliases
alias h='history'
alias j='jobs'
alias la='ls -lhAF'
alias ll='ls -lhF'
alias n='sudo netstat -ntlp'
alias s='python -m SimpleHTTPServer'

# git
alias ga='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch'
alias gg='git grep -I'
alias gi='git info'
alias gl='git pull'
alias glr='git pull --rebase'
alias gp='git push'
alias gpf='git push --force'
alias gr='git branch --remotes'
alias gs='git status'

# git workspace
alias gw='git workspace'
alias wf='git workspace fetch'
alias wi='git workspace info'
alias wl='git workspace pull'
alias wr='git workspace branch --remotes'

# vagrant
alias vd='vagrant destroy'
alias vg='vagrant global-status'
alias vh='vagrant halt'
alias vp='vagrant provision'
alias vr='vagrant reload'
alias vs='vagrant ssh -c "tmux a || tmux"'
alias vu='vagrant up'
