execute pathogen#infect()

set number

set hlsearch
set ignorecase
set smartcase

set nowrap

set tabstop=2
set expandtab
set shiftwidth=2

set colorcolumn=80

set list

autocmd BufRead,BufNewFile *.md,*.mdown,*.txt,COMMIT_EDITMSG setlocal spell spelllang=en_gb
