execute pathogen#infect()

set number

set hlsearch
set ignorecase
set smartcase

set tabstop=2
set expandtab
set shiftwidth=2

set colorcolumn=80,100

set nowrap

set list

setlocal spell spelllang=en_gb

autocmd BufRead,BufNewFile Vagrantfile set filetype=ruby
autocmd BufRead,BufNewFile Dockerfile set filetype=sh
