Vagrant.configure(2) do |config|
  config.vm.synced_folder "#{ENV['HOME']}/workspace/config_files", '/home/vagrant/.config_files', nfs: true

  config.vm.provision 'shell', path: File.join(File.dirname(__FILE__), 'setup.sh')
end
