Vagrant.configure(2) do |config|
  config.vm.synced_folder "#{ENV['HOME']}/workspace/config_files", '/home/vagrant/.config_files', nfs: true

  config.vm.provision :chef_apply do |chef|
    chef.recipe = <<EOF
package 'ctags'
package 'git'
package 'htop'
EOF
  end

  config.vm.provision 'shell', privileged: false, inline: '/home/vagrant/.config_files/bin/bootstrap'
end
